name: TG tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # daily 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Install Chrome WebDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Detected Chrome version: $CHROME_VERSION"
          sudo apt-get install -y unzip
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          if [ -z "$DRIVER_VERSION" ]; then
            echo "ChromeDriver version for $CHROME_VERSION not found!"
            exit 1
          fi
          echo "Downloading ChromeDriver version: $DRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          CI: true
        run: npm test
